# Generated by Django 5.1 on 2026-07-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteTag',
        ),
    ]
