# Generated by Django 5.1 on 2026-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_delete_quotetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
