name: Python CI — Unit Tests

on:
  push:
    branches:
      - main
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: src/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd src
          poetry install --no-interaction --no-root

      - name: Setup environment file
        run: |
          cd src
          cp .env.example .env

      - name: Run Django Tests
        run: |
          cd src
          poetry run python quotes_site/manage.py test
